services:
  db:
    image: pgvector/pgvector:pg15
    restart: always
    ports:
      - 6025:5432
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    command: |
      postgres -c log_statement=all
    environment:
      POSTGRES_PASSWORD: datathon
      POSTGRES_USER: datathon
      POSTGRES_DB: datathon

volumes:
  app-db-data:
