name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: gabsdevops
  GAR_LOCATION: us-central1
  REPOSITORY: datathon-api-globo-recommender
  SERVICE: datathon-api-globo-recommender
  REGION: us-central1
  DATABASE_URL: 34.59.187.129
  DATABASE_TABLE: datathon
  DATABASE_USERNAME: datathon-globo-db
  PYTHON_VERSION: "3.10"

jobs:
  deploy:
    # Add 'id-token' with the intended permissions for workload identity federation
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.5.1
          virtualenvs-create: true

      - name: Cache Poetry dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: GCP Auth
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: ${{ env.PROJECT_ID }}
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'


      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Download GCS files
        run: |
          gcloud storage cp gs://training-datathon-data/* ./datathon-globo-recommendation/datasources --recursive

      - name: Docker Auth - Artifact Registry
        id: docker-auth-json
        uses: 'docker/login-action@v1'
        with:
          registry: ${{ env.GAR_LOCATION }}-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCP_CREDENTIALS }}

      - name: Build and Push Docker Container
        run: |-
          cd datathon-globo-recommendation
          docker build -t "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}" ./
          docker push "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}"

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2.7.0
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          image: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}
          # postgresql://datathon:datathon@localhost:6025/{TABLE_NAME}
          env_vars: |
            DB_URL=postgresql://${{ env.DATABASE_USERNAME }}:${{ secrets.DATABASE_SECRET }}@${{ env.DATABASE_URL }}/${{ env.DATABASE_TABLE }}?host=/cloudsql/gabsdevops:datathon-globo-db
            ENVIRONMENT=production
            DB_PASSWORD=${{ secrets.DATABASE_SECRET }}

      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}
